### ISSUE TITLE
Help with converting

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/capitains_corpora_converter#4]
Hi Thibault,

Our GSoC student @suheb has given the capitains converter a run. It installs fine ([using these directions](https://github.com/cltk/capitains_corpora_converter#install-as-a-package)), but he's getting errors on cloning ([running this](https://github.com/cltk/capitains_corpora_converter#converting-open-greek-and-latins-csel)).

[This is the try/except being triggered](https://github.com/cltk/capitains_corpora_converter/blob/master/cltk_capitains_corpora_converter.py#L92).

``` python
2016-06-14 00:57:18,903 cltk_capitains_corpora_converter INFO     Cloning done.
2016-06-14 00:57:18,925 cltk_capitains_corpora_converter ERROR    Error parsing cloning/data/stoa0234e/__cts__.xml 
2016-06-14 00:57:18,925 cltk_capitains_corpora_converter ERROR    Error parsing cloning/data/stoa0180a/__cts__.xml 
2016-06-14 00:57:18,925 cltk_capitains_corpora_converter ERROR    Error parsing cloning/data/stoa0096/__cts__.xml 
2016-06-14 00:57:18,925 cltk_capitains_corpora_converter ERROR    Error parsing cloning/data/stoa0292d/__cts__.xml 
2016-06-14 00:57:18,925 cltk_capitains_corpora_converter ERROR    Error parsing cloning/data/stoa0045a/__cts__.xml 
2016-06-14 00:57:18,925 cltk_capitains_corpora_converter ERROR    Error parsing cloning/data/stoa0104c/__cts__.xml 
2016-06-14 00:57:18,926 cltk_capitains_corpora_converter ERROR    Error parsing cloning/data/tlg0526/__cts__.xml 
2016-06-14 00:57:18,926 cltk_capitains_corpora_converter ERROR    Error parsing cloning/data/stoa0223a/__cts__.xml 
2016-06-14 00:57:18,926 cltk_capitains_corpora_converter ERROR    Error parsing cloning/data/stoa0121g/__cts__.xml 
...
```

Thanks for your patience, our website code wasn't quite ready for all the Perseus texts, though it is now!

Any idea what's causing this? Thank you!

**Comment by PonteIneptique** [comment]
I'd need to add another level of debugging. Out of the blue I do not know what triggers that.

**Comment by PonteIneptique** [comment]
Could @suheb try it again using the branch `issue-5` ?

**Comment by kylepjohnson** [comment]
Thank you, Thibault. I'll have him give it a try and he will report here.

On Tuesday, June 14, 2016, Thibault Clérice <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Could @suheb https://github.com/suheb try it again using the branch
> issue-5 ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/cltk/capitains_corpora_converter/issues/4#issuecomment-225911591,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABxN-AYudg_tbPsijTspgtw_Z_G-E3fZks5qLsM6gaJpZM4I0tr1
> .

## 

Kyle P. Johnson, Ph.D.

Natural language processing, data science, architecture
https://kyle-p-johnson.comkyle@kyle-p-johnson.com |
https://kyle-p-johnson.com | https://github.com/kylepjohnson

Classical Language Toolkit, Founder
http://cltk.org | https://github.com/cltk/cltk

**Comment by suheb** [comment]
Hi @PonteIneptique, I got the following error using the `issue-5` branch:

```
2016-06-15 01:51:53,945 cltk_capitains_corpora_converter INFO     Cloning done.
2016-06-15 01:51:54,831 cltk_capitains_corpora_converter ERROR    Error parsing cloning/data/stoa0234e/__cts__.xml 
Traceback (most recent call last):
  File "/home/suheb/github-repos/cltk/capitains_corpora_converter/venv/bin/capitains-cltk-converter", line 9, in <module>
    load_entry_point('cltk-capitains-corpora-converter==0.0.1', 'console_scripts', 'capitains-cltk-converter')()
  File "build/bdist.linux-x86_64/egg/cltk_capitains_corpora_converter.py", line 260, in cmd
  File "build/bdist.linux-x86_64/egg/cltk_capitains_corpora_converter.py", line 221, in run
  File "build/bdist.linux-x86_64/egg/cltk_capitains_corpora_converter.py", line 152, in parse_directory
AttributeError: 'exceptions.TypeError' object has no attribute '__traceback__'
```

**Comment by PonteIneptique** [comment]
I have no idea what could be happening on your side except may be this question : are you using Python 2 ?

It seems I did not test at all with python2 and it could be that it does not work with it. I just saw that I did not recommend to use python 3.

**Comment by suheb** [comment]
Thanks, that was it. I installed the converter using python3 and it worked. (It's a good an idea to recommend using python3 in README) :+1:

**Comment by PonteIneptique** [comment]
Thanks @suheb . I'll close this issue as I move forward on #5 and #6

**Comment by kylepjohnson** [comment]
Thank you @PonteIneptique ! I'll let you know when we start using all these texts.
